kind: pipeline
type: docker
name: default

steps:
  - name: test-backend
    image: gradle:jdk8
    environment:
      DB_URL: "jdbc:postgresql://db:5432/blokatugent_test"
    commands:
      - cd backend
      - gradle assemble
      - gradle check

services:
  - name: db
    image: circleci/postgres:10.12-ram
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blokatugent_test
