kind: pipeline
type: docker
name: default

steps:
  - name: test-backend
    image: gradle:jdk8
    environment:
      SPRING_PROFILES_ACTIVE: ci
    commands:
      - apt-get update -y && apt-get install netcat -y
      - ./scripts/wait_for_service db 5432
      - cd backend
      - gradle assemble
      - gradle check

services:
  - name: db
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blokatugent_test
    commands:
      - sleep 15
      - echo *
      - ls -l
      - psql -c 'DROP SCHEMA IF EXISTS public cascade; CREATE SCHEMA public AUTHORIZATION postgres;' -d blokatugent_test
