version: "3.6"

volumes:
  backend_logs:
  pgdata:

services:
  backend:
    restart: always
    build: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: oap:11800
      TZ: Europe/Brussels
    depends_on:
      - db
    volumes:
      - backend_logs:/app/logs:rw
    networks:
      - blokat
    logging:
      options:
        max-size: "100m"
        max-file: "5"
  db:
    image: postgres:12-alpine
    command: postgres -c 'max_connections=500' -c 'shared_buffers=1024' -c 'log_min_messages=notice'
    restart: always
    environment:
      POSTGRES_DB: blokatugent
      POSTGRES_USER: blokat
      POSTGRES_PASSWORD: ***REMOVED***
      TZ: Europe/Brussels
      PGTZ: Europe/Brussels
    volumes:
      - pgdata:/var/lib/postgresql/data
    #  - ./backend/postgres.conf:/var/lib/postgresql/data/postgresql.conf

    networks:
      - blokat
    logging:
      options:
        max-size: "100m"
        max-file: "5"

  frontend:
    restart: always
    build: frontend
    ports:
      - "4242:80"
    networks:
      - blokat
    logging:
      options:
        max-size: "100m"
        max-file: "5"



networks:
  blokat:
    name: blokat
