version: "3"

services:
  web:
    build: backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: blokat
      POSTGRES_PASSWORD: "fdskl(§è§èmsdfcvzù)"
      POSTGRES_DB: blokatugent_test
